name: BackendTesting

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
  REPO_NAME: ${{ github.event.repository.name }}
  APP_ARGS: 'http://localhost:8081 http://localhost:8082 http://localhost:8083'

jobs:
  testing:
    runs-on: ubuntu-22.04
    name: Testing Backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean
          mvn package

      - name: Build Environment
        run: |
          if [ "${{env.REPO_NAME}}" != "orders-service" ]; then
              pwd 
              ls
              java -jar ${{ env.REPO_NAME }}-0.0.1-SNAPSHOT..jar         
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}/target/${{env.REPO_NAME}}-0.0.1-SNAPSHOT.jar --server.port=8081 &
          else
              gh repo clone ORT-FI-8184-TALLER-GRUPO3/products-service           
              mvn -f products-service/ -B package
              java -jar products-service/target/products-service-0.0.1-SNAPSHOT.jar --server.port=8081 &

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/shipping-service           
              mvn -f shipping-service/ -B package
              java -jar shipping-service/target/shipping-service-0.0.1-SNAPSHOT.jar --server.port=8082 &

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/payments-service           
              mvn -f payments-service/ -B package
              java -jar payments-service/target/payments-service-0.0.1-SNAPSHOT.jar --server.port=8083 &

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/${{env.REPO_NAME}}
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}/target/${{env.REPO_NAME}}-0.0.1-SNAPSHOT.jar ${{ env.APP_ARGS }} --server.port=8080 &
          fi    
      - name: Get JSON file with Postman Collection
        run: |
          curl -H 'Authorization: token ${{ env.GH_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -O -L 'https://raw.githubusercontent.com/ORT-FI-8184-TALLER-GRUPO3/Devops/main/TestingBackend/testing-backend-service.json'
          
      - name: Run Jar for Functional Testing newman
        run: | 
          newman run testing-backend-service.json

