name: BackendTesting

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
  REPO_NAME: ${{ github.event.repository.name }}
  APP_ARGS: 'http://localhost:8081 http://localhost:8082 http://localhost:8083'

jobs:
  testing:
    runs-on: ubuntu-22.04
    name: Testing Backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean
          mvn package

      - name: Build Environment
        run: |
          if [ "${{env.REPO_NAME}}" != "orders-service" ]; then
              gh repo clone ORT-FI-8184-TALLER-GRUPO3/${{env.REPO_NAME}}          
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}/target/${{env.REPO_NAME}}.jar --server.port=8081&
          else
              git clone https://github.com/ORT-FI-8184-TALLER-GRUPO3/products-service
              cd products-service 
              mvn package 
              java -Dserver.port=8888 -jar target/products-service-0.0.1-SNAPSHOT-spring-boot.jar -DskipTest &
              sleep 5
              cd .. 
              git clone https://github.com/ORT-FI-8184-TALLER-GRUPO3/shipping-service
              cd shipping-service 
              mvn package 
              java -Dserver.port=8887 -jar target/shipping-service-0.0.1-SNAPSHOT-spring-boot.jar -DskipTest &
              sleep 5
              cd ..
              git clone https://github.com/ORT-FI-8184-TALLER-GRUPO3/payments-service 
              cd payments-service 
              mvn package 
              java -Dserver.port=8886 -jar target/payments-service0.0.1-SNAPSHOT-spring-boot.jar -DskipTest &
              sleep 5
              cd .. 
              java -jar target/${{ env.SERVICE_NAME }}-0.0.1-SNAPSHOT-spring-boot.jar http://localhost:8886 http://localhost:8887 http://localhost:8888 --server.port=8885&
              sleep 5
          fi    
          run: |
          curl -H 'Authorization: token ${{ env.GH_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -O -L 'https://raw.githubusercontent.com/ORT-FI-8184-TALLER-GRUPO3/Devops/main/TestingBackend/testing-backend-service.json'
          newman run testing-backend-service.json