name: BackendTesting

on:
  workflow_call:

env:
  GH_TOKEN: ${{ github.token }}
#  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
  POSTMAN_API_KEY: PMAK-6579143cf938a673eb62ed4e-e019040d8cab3615510f1cefc4befefabe
  REPO_NAME: ${{ github.event.repository.name }}
  APP_ARGS: 'http://localhost:8081 http://localhost:8082 http://localhost:8083'

jobs:
  testing:
    runs-on: ubuntu-22.04
    name: Testing Backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean
          mvn package

      - name: Build Environment
        run: |
          if [ "${{env.REPO_NAME}}" != "orders-service" ]; then
              gh repo clone ORT-FI-8184-TALLER-GRUPO3/${{env.REPO_NAME}} 
              cd ${{env.REPO_NAME}}         
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}/target/${{env.REPO_NAME}}.jar --server.port=8081
              sleep 5
              cd ..
          else
              gh repo clone ORT-FI-8184-TALLER-GRUPO3/products-service 
              ls
              cd products-service          
              ls
              mvn -f products-service/ -B package
              java -jar products-service/target/products-service.jar --server.port=8081sleep 5
              cd .. 

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/shipping-service    
              cd shipping-service       
              mvn -f shipping-service/ -B package
              java -jar shipping-service/target/shipping-service.jar --server.port=8082sleep 5
              cd ..

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/payments-service   
              cd payments-service
              mvn -f payments-service/ -B package
              java -jar payments-service/target/payments-service.jar --server.port=8083sleep 5
              cd ..

              gh repo clone ORT-FI-8184-TALLER-GRUPO3/${{env.REPO_NAME}}
              cd ${{env.REPO_NAME}}
              mvn -f ${{env.REPO_NAME}}/ -B package
              java -jar ${{env.REPO_NAME}}-service/target/${{env.REPO_NAME}}-service.jar ${{ env.APP_ARGS }} --server.port=8084sleep 5
              cd ..
          fi    

      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ env.POSTMAN_API_KEY }}

      - name: Get JSON file with Postman Collection
        run: |
          curl -H 'Authorization: token ${{ env.GH_TOKEN }}' \
          -H 'Accept: application/vnd.github.v3.raw' \
          -O -L 'https://raw.githubusercontent.com/ORT-FI-8184-TALLER-GRUPO3/Devops/main/TestingBackend/testing-backend-service.json'
     
      - name: Obtener IP del Host
        run: |
          HOST_IP=$(ip route show default | awk '/default/ {print $3}')
          echo "La IP del host es: $HOST_IP"
          
      - name: Run Postman CLI backend testing
        run: 
          pwd &
          ls &
          postman collection run testing-backend-service.json
