name: Github Action Frontend

on:
  push:
    branches:
      - Dev
      - Test
      - Prod
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SonarTest:
    uses: ./.github/workflows/sonarscan-frontend.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy:
    needs: SonarTest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [Dev, Test, Prod]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: echo "CI_ENV=${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Build and Deploy
        uses: ./.github/workflows/deploy-to-s3.yml
        with:
          CI_ENV: ${{ env.CI_ENV }}
          CONTENTFUL_ENVIRONMENT: ${{ env.CI_ENV }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets["AWS_ACCESS_KEY_ID_" + env.CI_ENV] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets["AWS_SECRET_ACCESS_KEY_" + env.CI_ENV] }}
          AWS_SESSION_TOKEN: ${{ secrets["AWS_SESSION_TOKEN_" + env.CI_ENV] }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_ORIGIN_BUCKET: ${{ secrets["S3_ORIGIN_BUCKET_" + env.CI_ENV] }}
