name: Reusable Java CI/CD

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      target:
        required: true
        type: string
      pom_path:
        required: false
        type: string
        default: './pom.xml'
      SONAR_PROJECT:
        required: true
        type: string

jobs:
  SonarTest:
    uses: ./.github/workflows/sonarscan_backends.yml
    with:
      SONAR_PROJECT: ${{ inputs.SONAR_PROJECT }}  
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build-and-deploy:
    needs: SonarTest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file ${{ inputs.pom_path }} -DskipTests

    - name: Build Docker Image
      run: docker build -t "$(echo "${{ inputs.service }}-${{ inputs.target }}:${{ github.sha }}" | tr '[:upper:]' '[:lower:]')" .
