name: Reusable Java CI/CD

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      target:
        required: true
        type: string
      pom_path:
        required: false
        type: string
        default: './pom.xml' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file ${{ inputs.pom_path }}

    - name: Build Docker Image
      run: docker build -t ${{ inputs.service }}-${{ inputs.target }}:${{ github.sha }} .


