name: Github Action Frontend

on:
  workflow_call:
    inputs:
      service:
        required: false
        type: string
      target:
        required: false
        type: string
      pom_path:
        required: false
        type: string
        default: './pom.xml' 

jobs:
  SonarTest:
    uses: ./.github/workflows/sonarscan-frontend.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-and-deploy:
    needs: SonarTest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Environment Variables
        run: echo "CI_ENV=${{ matrix.environment }}" >> $GITHUB_ENV

      - name: Build and Deploy
        uses: ./.github/workflows/s3deploy-frontend.yml
        with:
          CI_ENV: ${{ env.CI_ENV }}
          branch_name: ${{ env.NAME }}
          CONTENTFUL_ENVIRONMENT: ${{ env.CI_ENV }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_ + env.CI_ENV }}

