name: Github Action Frontend

on:
  workflow_call:
    inputs:
      service:
        required: false
        type: string
      target:
        required: false
        type: string
      pom_path:
        required: false
        type: string
        default: './pom.xml' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Test code
        run: npm run test

      - name: Build app
        run: npm run build
        
  AnalisisSonarQube:
    needs: build
    name: AnalisisSonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Set Branch Input
        id: set_branch
        run: echo "BRANCH_NAME=${{ github.event.inputs.branch_name }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run SonarQube Analysis
        run: ./sonar-scan.sh ${{ env.BRANCH_NAME }}
        
  DeployToS3:
    needs: AnalisisSonarQube
    name: DeployToS3
    uses: ./.github/workflows/deploy-to-s3.yml
    with:
      CI_ENV: Prod
      CONTENTFUL_ENVIRONMENT: 'Prod'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_PROD }}
