name: Github Action Frontend

on:
  workflow_call:
    inputs:
      bucket:
        required: true
        type: string

jobs:
  SonarQubeAnalisis:
    name: SonarQubeAnalisis
    uses: ./.github/workflows/sonarscan-frontend.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  DeployToS3:
    name: DeployToS3
    needs: SonarQubeAnalisis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to S3
        run: |
          echo "CI_ENV=${{ inputs.branchname }}"
          # Add your deployment commands here

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ inputs.bucket }}
