name: Github Action Frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      
      - name: Test code
        run: npm run test

      - name: Build app
        run: npm run build
        
  AnalisisSonarQube:
    needs: build
    uses: ./.github/workflows/sonarscan-frontend.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  DeployToS3:
    needs: AnalisisSonarQube
    name: DeployToS3
    
    uses: ./.github/workflows/s3deploy-frontend.yml
    with:
      CI_ENV: ${{ env.CI_ENV }}
      CONTENTFUL_ENVIRONMENT: ${{ env.CI_ENV }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{secrets.S3_ORIGIN_BUCKET}}
