name: Github Action Workflow DEV

on:
  workflow_call:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SonarTest:
    uses: ./.github/workflows/sonarscan_frontend.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build-dev:
    needs: SonarTest
    uses: ./.github/workflows/deploy-to-s3_frontend.yml
    with:
      CI_ENV: dev
      CONTENTFUL_ENVIRONMENT: 'dev'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET_DEV }}
